spring:
  application:
    name: config-server-git
  profiles:
    active: git
  cloud:
    config:
      server:
        git:
          # public repo doesn't need auth
          uri: https://github.com/w22116972/spring-config-server.git
          # what the path in Git is to look for config files
          search-paths: src/main/resources/config
          clone-on-start: true
server:
  port: 8888